/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MdxPublicImport } from './routes/mdxPublic'
import { Route as CombinedMdxImport } from './routes/combined-mdx'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPublicLessonsImport } from './routes/_authenticated/public-lessons'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMdxImport } from './routes/_authenticated/mdx'
import { Route as AuthenticatedLessonPlanImport } from './routes/_authenticated/lesson-plan'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'

// Create/Update Routes

const MdxPublicRoute = MdxPublicImport.update({
  path: '/mdxPublic',
  getParentRoute: () => rootRoute,
} as any)

const CombinedMdxRoute = CombinedMdxImport.update({
  path: '/combined-mdx',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPublicLessonsRoute = AuthenticatedPublicLessonsImport.update(
  {
    path: '/public-lessons',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMdxRoute = AuthenticatedMdxImport.update({
  path: '/mdx',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLessonPlanRoute = AuthenticatedLessonPlanImport.update({
  path: '/lesson-plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/combined-mdx': {
      preLoaderRoute: typeof CombinedMdxImport
      parentRoute: typeof rootRoute
    }
    '/mdxPublic': {
      preLoaderRoute: typeof MdxPublicImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/lesson-plan': {
      preLoaderRoute: typeof AuthenticatedLessonPlanImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/mdx': {
      preLoaderRoute: typeof AuthenticatedMdxImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/public-lessons': {
      preLoaderRoute: typeof AuthenticatedPublicLessonsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedDashboardRoute,
    AuthenticatedLessonPlanRoute,
    AuthenticatedMdxRoute,
    AuthenticatedProfileRoute,
    AuthenticatedPublicLessonsRoute,
    AuthenticatedIndexRoute,
  ]),
  AboutRoute,
  CombinedMdxRoute,
  MdxPublicRoute,
])

/* prettier-ignore-end */
